version: "3.9"

services:
    app:
        container_name: app
        image: ghcr.io/ehasnain/my-server
        build: .
        restart: always
    app-local:
        container_name: app-run
        image: ghcr.io/ehasnain/my-server
        build: .
        restart: always
        ports:
            - "${PORT}:20965"
